spring:
  application:
      name: football-api


jwt:
  secret: secret

api:
  url: https://apiv2.apifootball.com?action=get_standing
  key: 9bb66184e0c8145384fd2cc0f7b914ada57b4e8fd2e4d6d586adcc27c257a978


---
spring:
  config:
    activate:
      on-profile: docker
---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8080
---
